export const STAGE_NODE_WIDTH = 300
export const STAGE_NODE_MARGIN_HORIZONTAL = 50
export const STAGE_NODE_MARGIN_VERTICAL = 30

export const STAGE_NODE_BASE_PADDING = 10
export const STAGE_NODE_TOP_CONTENT_HEIGHT = 322
export const STAGE_NODE_ADD_OPTION_BUTTON_HEIGHT = 24

export const STAGE_NODE_OPTION_ITEM_WIDTH = 244
export const STAGE_NODE_OPTION_ITEM_HEIGHT = 46
export const STAGE_NODE_OPTION_ITEM_LEFT = 38

export const calcStageNodeHeight = (menuCount: number) =>
  STAGE_NODE_BASE_PADDING +
  STAGE_NODE_TOP_CONTENT_HEIGHT +
  STAGE_NODE_ADD_OPTION_BUTTON_HEIGHT +
  Math.max(0, menuCount) * STAGE_NODE_OPTION_ITEM_HEIGHT
